// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: DockerProjectCommon.proto

package dockerProjectProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqSeq string `protobuf:"bytes,1,opt,name=reqSeq,proto3" json:"reqSeq,omitempty"` // 请求序列号，全局唯一
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DockerProjectCommon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_DockerProjectCommon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_DockerProjectCommon_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetReqSeq() string {
	if x != nil {
		return x.ReqSeq
	}
	return ""
}

func (x *RequestHeader) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  uint32 `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DockerProjectCommon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_DockerProjectCommon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_DockerProjectCommon_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetErrno() uint32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ResponseHeader) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type GetItemInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqHeader *RequestHeader `protobuf:"bytes,1,opt,name=reqHeader,proto3" json:"reqHeader,omitempty"`
	ItemId    int64          `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"` //商品id
}

func (x *GetItemInfoReq) Reset() {
	*x = GetItemInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DockerProjectCommon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoReq) ProtoMessage() {}

func (x *GetItemInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_DockerProjectCommon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoReq.ProtoReflect.Descriptor instead.
func (*GetItemInfoReq) Descriptor() ([]byte, []int) {
	return file_DockerProjectCommon_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemInfoReq) GetReqHeader() *RequestHeader {
	if x != nil {
		return x.ReqHeader
	}
	return nil
}

func (x *GetItemInfoReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetItemInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespHeader      *ResponseHeader `protobuf:"bytes,1,opt,name=respHeader,proto3" json:"respHeader,omitempty"`
	Id              int64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ItemSourceName  string          `protobuf:"bytes,3,opt,name=itemSourceName,proto3" json:"itemSourceName,omitempty"`    // 商品英文名称
	ItemCnName      string          `protobuf:"bytes,4,opt,name=itemCnName,proto3" json:"itemCnName,omitempty"`            // 商品中文名称
	SellOnlineCount int32           `protobuf:"varint,5,opt,name=sellOnlineCount,proto3" json:"sellOnlineCount,omitempty"` // 在售数量
	PicUrl          string          `protobuf:"bytes,6,opt,name=picUrl,proto3" json:"picUrl,omitempty"`                    // 商品图片
	Prices          float32         `protobuf:"fixed32,7,opt,name=prices,proto3" json:"prices,omitempty"`                  //当前价格
	Currency        string          `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`                //货币类型
	Addtime         int64           `protobuf:"varint,9,opt,name=addtime,proto3" json:"addtime,omitempty"`                 //添加时间
	Modifytime      string          `protobuf:"bytes,10,opt,name=modifytime,proto3" json:"modifytime,omitempty"`           //修改时间
}

func (x *GetItemInfoResp) Reset() {
	*x = GetItemInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DockerProjectCommon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoResp) ProtoMessage() {}

func (x *GetItemInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_DockerProjectCommon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoResp.ProtoReflect.Descriptor instead.
func (*GetItemInfoResp) Descriptor() ([]byte, []int) {
	return file_DockerProjectCommon_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemInfoResp) GetRespHeader() *ResponseHeader {
	if x != nil {
		return x.RespHeader
	}
	return nil
}

func (x *GetItemInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetItemInfoResp) GetItemSourceName() string {
	if x != nil {
		return x.ItemSourceName
	}
	return ""
}

func (x *GetItemInfoResp) GetItemCnName() string {
	if x != nil {
		return x.ItemCnName
	}
	return ""
}

func (x *GetItemInfoResp) GetSellOnlineCount() int32 {
	if x != nil {
		return x.SellOnlineCount
	}
	return 0
}

func (x *GetItemInfoResp) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *GetItemInfoResp) GetPrices() float32 {
	if x != nil {
		return x.Prices
	}
	return 0
}

func (x *GetItemInfoResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetItemInfoResp) GetAddtime() int64 {
	if x != nil {
		return x.Addtime
	}
	return 0
}

func (x *GetItemInfoResp) GetModifytime() string {
	if x != nil {
		return x.Modifytime
	}
	return ""
}

var File_DockerProjectCommon_proto protoreflect.FileDescriptor

var file_DockerProjectCommon_proto_rawDesc = []byte{
	0x0a, 0x19, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x71, 0x53, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x22, 0x69, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x3f, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x71, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0xdd, 0x02, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x42, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x74, 0x65, 0x6d, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x74, 0x65,
	0x6d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x74, 0x65, 0x6d, 0x43, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x65, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x65, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x64,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DockerProjectCommon_proto_rawDescOnce sync.Once
	file_DockerProjectCommon_proto_rawDescData = file_DockerProjectCommon_proto_rawDesc
)

func file_DockerProjectCommon_proto_rawDescGZIP() []byte {
	file_DockerProjectCommon_proto_rawDescOnce.Do(func() {
		file_DockerProjectCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_DockerProjectCommon_proto_rawDescData)
	})
	return file_DockerProjectCommon_proto_rawDescData
}

var file_DockerProjectCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_DockerProjectCommon_proto_goTypes = []any{
	(*RequestHeader)(nil),   // 0: dockerProjectProto.RequestHeader
	(*ResponseHeader)(nil),  // 1: dockerProjectProto.ResponseHeader
	(*GetItemInfoReq)(nil),  // 2: dockerProjectProto.GetItemInfoReq
	(*GetItemInfoResp)(nil), // 3: dockerProjectProto.GetItemInfoResp
}
var file_DockerProjectCommon_proto_depIdxs = []int32{
	0, // 0: dockerProjectProto.GetItemInfoReq.reqHeader:type_name -> dockerProjectProto.RequestHeader
	1, // 1: dockerProjectProto.GetItemInfoResp.respHeader:type_name -> dockerProjectProto.ResponseHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_DockerProjectCommon_proto_init() }
func file_DockerProjectCommon_proto_init() {
	if File_DockerProjectCommon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DockerProjectCommon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DockerProjectCommon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DockerProjectCommon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetItemInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DockerProjectCommon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetItemInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DockerProjectCommon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DockerProjectCommon_proto_goTypes,
		DependencyIndexes: file_DockerProjectCommon_proto_depIdxs,
		MessageInfos:      file_DockerProjectCommon_proto_msgTypes,
	}.Build()
	File_DockerProjectCommon_proto = out.File
	file_DockerProjectCommon_proto_rawDesc = nil
	file_DockerProjectCommon_proto_goTypes = nil
	file_DockerProjectCommon_proto_depIdxs = nil
}
