// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: DockerProjectAo.proto

package dockerProjectProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerProjectAo_GetItemInfo_FullMethodName = "/dockerProjectProto.DockerProjectAo/GetItemInfo"
)

// DockerProjectAoClient is the client API for DockerProjectAo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerProjectAoClient interface {
	// 获取商品信息
	GetItemInfo(ctx context.Context, in *GetItemInfoReq, opts ...grpc.CallOption) (*GetItemInfoResp, error)
}

type dockerProjectAoClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerProjectAoClient(cc grpc.ClientConnInterface) DockerProjectAoClient {
	return &dockerProjectAoClient{cc}
}

func (c *dockerProjectAoClient) GetItemInfo(ctx context.Context, in *GetItemInfoReq, opts ...grpc.CallOption) (*GetItemInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemInfoResp)
	err := c.cc.Invoke(ctx, DockerProjectAo_GetItemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerProjectAoServer is the server API for DockerProjectAo service.
// All implementations must embed UnimplementedDockerProjectAoServer
// for forward compatibility.
type DockerProjectAoServer interface {
	// 获取商品信息
	GetItemInfo(context.Context, *GetItemInfoReq) (*GetItemInfoResp, error)
	mustEmbedUnimplementedDockerProjectAoServer()
}

// UnimplementedDockerProjectAoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerProjectAoServer struct{}

func (UnimplementedDockerProjectAoServer) GetItemInfo(context.Context, *GetItemInfoReq) (*GetItemInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemInfo not implemented")
}
func (UnimplementedDockerProjectAoServer) mustEmbedUnimplementedDockerProjectAoServer() {}
func (UnimplementedDockerProjectAoServer) testEmbeddedByValue()                         {}

// UnsafeDockerProjectAoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerProjectAoServer will
// result in compilation errors.
type UnsafeDockerProjectAoServer interface {
	mustEmbedUnimplementedDockerProjectAoServer()
}

func RegisterDockerProjectAoServer(s grpc.ServiceRegistrar, srv DockerProjectAoServer) {
	// If the following call pancis, it indicates UnimplementedDockerProjectAoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerProjectAo_ServiceDesc, srv)
}

func _DockerProjectAo_GetItemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerProjectAoServer).GetItemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerProjectAo_GetItemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerProjectAoServer).GetItemInfo(ctx, req.(*GetItemInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerProjectAo_ServiceDesc is the grpc.ServiceDesc for DockerProjectAo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerProjectAo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dockerProjectProto.DockerProjectAo",
	HandlerType: (*DockerProjectAoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemInfo",
			Handler:    _DockerProjectAo_GetItemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DockerProjectAo.proto",
}
