// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: DockerGoProjectConst.proto

package dockerGoProjectProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//请求类型
type RequestType int32

const (
	RequestType_REQUEST_TYPE_COMMON RequestType = 0 // 默认请求（直接调用）
	RequestType_REQUEST_TYPE_GRPC   RequestType = 1 // grpc请求
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_COMMON",
		1: "REQUEST_TYPE_GRPC",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_COMMON": 0,
		"REQUEST_TYPE_GRPC":   1,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_DockerGoProjectConst_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_DockerGoProjectConst_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_DockerGoProjectConst_proto_rawDescGZIP(), []int{0}
}

// 用户校验类型
type ValidUserType int32

const (
	ValidUserType_VALID_USER_TYPE_COMMON     ValidUserType = 0 //默认类型
	ValidUserType_VALID_USER_TYPE_BLACK_LIST ValidUserType = 1 //黑名单用户
	ValidUserType_VALID_USER_TYPE_WHITE_LIST ValidUserType = 2 //白名单用户
)

// Enum value maps for ValidUserType.
var (
	ValidUserType_name = map[int32]string{
		0: "VALID_USER_TYPE_COMMON",
		1: "VALID_USER_TYPE_BLACK_LIST",
		2: "VALID_USER_TYPE_WHITE_LIST",
	}
	ValidUserType_value = map[string]int32{
		"VALID_USER_TYPE_COMMON":     0,
		"VALID_USER_TYPE_BLACK_LIST": 1,
		"VALID_USER_TYPE_WHITE_LIST": 2,
	}
)

func (x ValidUserType) Enum() *ValidUserType {
	p := new(ValidUserType)
	*p = x
	return p
}

func (x ValidUserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidUserType) Descriptor() protoreflect.EnumDescriptor {
	return file_DockerGoProjectConst_proto_enumTypes[1].Descriptor()
}

func (ValidUserType) Type() protoreflect.EnumType {
	return &file_DockerGoProjectConst_proto_enumTypes[1]
}

func (x ValidUserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidUserType.Descriptor instead.
func (ValidUserType) EnumDescriptor() ([]byte, []int) {
	return file_DockerGoProjectConst_proto_rawDescGZIP(), []int{1}
}

var File_DockerGoProjectConst_proto protoreflect.FileDescriptor

var file_DockerGoProjectConst_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x6f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x47, 0x6f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x3d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x50, 0x43, 0x10,
	0x01, 0x2a, 0x6b, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x1e,
	0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x1e,
	0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x57, 0x48, 0x49, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x02, 0x42, 0x17,
	0x5a, 0x15, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x6f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DockerGoProjectConst_proto_rawDescOnce sync.Once
	file_DockerGoProjectConst_proto_rawDescData = file_DockerGoProjectConst_proto_rawDesc
)

func file_DockerGoProjectConst_proto_rawDescGZIP() []byte {
	file_DockerGoProjectConst_proto_rawDescOnce.Do(func() {
		file_DockerGoProjectConst_proto_rawDescData = protoimpl.X.CompressGZIP(file_DockerGoProjectConst_proto_rawDescData)
	})
	return file_DockerGoProjectConst_proto_rawDescData
}

var file_DockerGoProjectConst_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_DockerGoProjectConst_proto_goTypes = []any{
	(RequestType)(0),   // 0: dockerGoProjectProto.RequestType
	(ValidUserType)(0), // 1: dockerGoProjectProto.ValidUserType
}
var file_DockerGoProjectConst_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DockerGoProjectConst_proto_init() }
func file_DockerGoProjectConst_proto_init() {
	if File_DockerGoProjectConst_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DockerGoProjectConst_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DockerGoProjectConst_proto_goTypes,
		DependencyIndexes: file_DockerGoProjectConst_proto_depIdxs,
		EnumInfos:         file_DockerGoProjectConst_proto_enumTypes,
	}.Build()
	File_DockerGoProjectConst_proto = out.File
	file_DockerGoProjectConst_proto_rawDesc = nil
	file_DockerGoProjectConst_proto_goTypes = nil
	file_DockerGoProjectConst_proto_depIdxs = nil
}
